(function(g){var window=this;var R1,S1=function(a){var b={languageCode:a.languageCode,languageName:a.languageName,displayName:g.PH(a),kind:a.kind,name:a.name,id:a.id,is_servable:a.u,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.vssId};a.translationLanguage&&(b.translationLanguage=a.translationLanguage);return b},T1=function(a){return a.translationLanguage?a.translationLanguage.languageCode:a.languageCode},$Ea=function(a,b){var c=new g.OH;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.u=a.u;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},aFa=function(){this.B=[];
this.u=[]},U1=function(a,b){return b?a.u.concat(a.B):a.u},V1=function(a,b){switch(b.kind){case "asr":bFa(b,a.B);
break;default:bFa(b,a.u)}},bFa=function(a,b){g.db(b,function(c){return c?a.toString()===c.toString():!1})||b.push(a)},W1=function(){g.B.call(this);
this.B=new aFa;this.F=[]},X1=function(a,b,c){W1.call(this,a);
this.audioTrack=c;this.u=null;this.F=b.lE},Y1=function(){this.segments=[]},cFa=function(a,b){var c=g.xb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.kb(a.segments,c),g.kb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.tb(a.segments,c,0,b),g.tb(a.segments,c+1,0,b)))},Z1=function(a,b,c,d,e,f){g.B.call(this);
this.policy=a;this.player=b;this.W=c;this.I=d;this.F=e;this.L=f;this.U=this.player.S();this.D=new Y1;this.B=this.C=this.u=null;this.K=new g.D(this.nE,1E3,this);this.events=new g.pO(this);g.C(this,this.K);g.C(this,this.events);this.events.P(b,"SEEK_COMPLETE",this.QE);this.QE();this.nE()},dFa=function(a,b){var c=g.$w(g.lx(b,a.policy,{})),d={format:"RAW",
withCredentials:!0};a.F&&(d.responseType="arraybuffer");a.B=g.mt(c,d,3,100).then(function(e){a:{a.ma();if(a.C){var f=!(a.F?e.response:e.responseText)||400<=e.status,h=g.NB(e);if(h){e=g.lx(a.C,a.policy,{});f=a.C;g.gx(f.B,e,h);f.requestId=e.get("req_id");dFa(a,a.C);break a}f||null==a.I||(h=a.C.u[0],a.F?a.I(e.response,1E3*(h.startTime+a.player.Ac())):a.I(e.responseText,1E3*(h.startTime+a.player.Ac())))}a.C=null;a.B=null}});
a.C=b;cFa(a.D,a.C.u[0].xa)},$1=function(a,b){W1.call(this,b.S());
this.u=a;this.J=b;this.C=null;this.D=!1;this.I=g.mE(this.J.S())&&!this.u.isManifestless},eFa=function(a,b){var c=[],d;
for(d in a.u.u)if(a.u.u.hasOwnProperty(d)){var e=a.u.u[d];if(g.AO(e,b||null)){var f="en",h="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;c.push(new g.OH({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},fFa=function(a,b){return null!=b&&b in a.u.u?a.u.u[b]:null},gFa=function(a,b,c){var d=[],e;
for(e in a.u.u)if(a.u.u.hasOwnProperty(e)){var f=a.u.u[e];if(g.AO(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},a2=function(a,b,c,d,e){W1.call(this,e||null);
this.videoId=b;this.MD=d;this.D={};this.u=null;b=c||g.fq(a).hl||"";b=b.split("_").join("-");this.C=g.hq(a,{hl:b})},b2=function(a,b,c,d,e,f,h){var l={};
g.Sa(l,b);g.Sa(l,a.params);g.Sa(l,c);var m={};g.Sa(m,b.Jc);a.params.Jc&&g.Sa(m,a.params.Jc);g.Sa(m,c.Jc);l.Jc=m;g.U.call(this,{G:"div",N:"caption-window",T:{id:"caption-window-"+a.id,dir:1===l.Ve?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:l.lang},R:[{G:"span",N:"captions-text",T:{style:"word-wrap: normal; display: block;"}}]});this.F=[];this.aa=!1;this.B=a;this.ga=this.da=null;this.playerWidth=e;this.playerHeight=f;this.experiments=h;this.I=null;this.maxWidth=.96*e;this.Ia=.96*f;this.u=
l;this.jb=c;this.D=this.ha("captions-text");this.Ua=""!==this.D.style.getPropertyValue("box-decoration-break")||""!==this.D.style.getPropertyValue("-webkit-box-decoration-break");this.ea=d/360*16;this.type=0;this.ya=this.ea*hFa(m);a=new g.Rt(this.element,!0);g.C(this,a);a.subscribe("dragstart",this.UL,this);a.subscribe("dragmove",this.TL,this);a.subscribe("dragend",this.SL,this);this.Fa=this.Aa=0;b="";this.u.windowOpacity&&(a=g.z_(this.u.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.u.windowOpacity+
")");a={"background-color":b,display:!1===this.u.isVisible?"none":"","text-align":iFa[this.u.textAlign]};this.Ua&&(a["border-radius"]=b?this.ya/8+"px":"");if(this.C=2===this.B.params.Ve||3===this.B.params.Ve)b=this.element,c="vertical-rl",1===this.u.GA&&(c="vertical-lr"),g.Ae&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.ug(b,"-o-writing-mode",c),g.ug(b,"-webkit-writing-mode",c),g.ug(b,"writing-mode",c),g.ug(b,"text-orientation","upright"),g.G(b,"ytp-vertical-caption"),3===this.B.params.Ve&&(g.ug(b,"text-orientation",
""),g.ug(b,"transform","rotate(180deg)"));g.ug(this.element,a);switch(this.u.Wh){case 0:case 1:case 2:g.G(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.G(this.element,"ytp-caption-window-bottom")}},hFa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},jFa=function(a,b){var c={},d=b.background?b.background:a.u.Jc.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.u.Jc.backgroundOpacity;d=g.z_(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Ua&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ya/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.ea*hFa(b)+"px";d=1;e=b.color||a.u.Jc.color;if(b.color||null!=b.textOpacity)e=g.z_(e),d=null==b.textOpacity?a.u.Jc.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.mx&&(h=e=b.mx);var l=a.ea/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Zq()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.u.Jc.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.ii&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.AK&&(c.visibility="hidden");1===b.HD&&a.C&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.rE||g.xr,3===a.B.params.Ve?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Gi||2===b.Gi||3===b.Gi||4===b.Gi||5===b.Gi)if(g.rE)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Gi){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},kFa=function(a){a.I=g.He("SPAN");
g.ug(a.I,{display:"block"});g.G(a.I,"caption-visual-line");a.D.appendChild(a.I)},lFa=function(a,b){var c=g.He("SPAN");
g.ug(c,{display:"inline-block","white-space":"pre-wrap"});g.ug(c,jFa(a,b));c.classList.add("ytp-caption-segment");a.I.appendChild(c);c.previousElementSibling&&(g.ug(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.ug(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},mFa=function(a,b,c){a.aa=a.aa||!!c;
var d={};g.Sa(d,a.u.Jc);g.Sa(d,c||b.u);g.Sa(d,a.jb.Jc);(c=!a.I)&&kFa(a);for(var e=a.da&&a.ga&&g.Ub(d,a.ga)?a.da:lFa(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(kFa(a),e=lFa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Ie(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.rE||!g.yg(n.children[2],"text-emphasis")||(m=a.C?"padding-right":"padding-top",g.yg(n.children[2],"text-emphasis-position")&&(m=a.C?"padding-left":"padding-bottom"),
g.Ce?g.ug(e,m,"1em"):g.ug(e,m,"0.5em")))}a.ga=d;a.da=e;a.F.push(b)},c2=function(a,b,c,d,e,f,h){b2.call(this,a,b,c,d,e,f,h);
this.type=1},d2=function(a,b,c,d,e,f,h){b2.call(this,a,b,c,d,e,f,h);
this.type=2;this.K=[];this.W=this.L=this.ka=0;this.X=NaN;this.Oa=0;this.Xa=null;this.la=new g.D(this.xP,433,this);g.G(this.element,"ytp-caption-window-rollup");g.C(this,this.la);g.ug(this.element,"overflow","hidden")},nFa=function(a,b){if(!b)return"";
a.C&&1!==a.B.params.GA&&(b*=-1);return"translate"+(a.C?"X":"Y")+"("+b+"px)"},oFa=function(a){a.K=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.B.params.Lk,c=0,d=0,e=a.K.length-1;c<b&&-1<e;){var f=a.K[e];d+=a.C?f.offsetWidth:f.offsetHeight;c++;e--}a.K.length<b&&(d*=b/a.K.length);a.L=d;b=Math;c=b.max;isNaN(a.X)&&((d=a.u.kl)?(e=g.He("SPAN"),g.Pe(e,"\u2013".repeat(d)),g.ug(e,jFa(a,a.u.Jc)),a.D.appendChild(e),a.X=e.offsetWidth,a.D.removeChild(e)):a.X=0);d=a.D;a.W=c.call(b,a.X,a.Oa,(a.C?d.offsetHeight:d.offsetWidth)+1)},pFa=function(a,b){oFa(a);
var c=a.K.reduce(function(e,f){return(a.C?f.offsetWidth:f.offsetHeight)+e},0);
c=a.L-c;if(c!==a.ka){var d=0<c&&0===a.ka;b||isNaN(c)||d||(g.G(a.element,"ytp-rollup-mode"),g.qn(a.la));g.ug(a.D,"transform",nFa(a,c));a.ka=c}oFa(a)},e2=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.FG.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.u=h},f2=function(a,b,c,d,e){g.FG.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.u=[]},qFa=function(a){var b="_"+g2++;
return new f2(0,0x8000000000000,0,b,a)},sFa=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.Bd){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=rFa(l.textContent,n.textContent,p.textContent,f.textContent,h);return new e2(a,b,e,c,l,d,m)}switch(m.Bd){case 9:case 10:m.Gi=1;break;case 11:m.Gi=2;break;case 12:m.Gi=3;break;case 13:m.Gi=4;break;case 14:m.Gi=5}return new e2(a,b,e,c,l.textContent||"",d,m)},rFa=function(a,b,c,d,e){var f=g.Zq(),h=
f?g.He("DIV"):g.He("RUBY"),l=g.He("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.He("DIV"):g.He("RP");a.textContent=b;h.appendChild(a);b=f?g.He("DIV"):g.He("RT");b.textContent=c;h.appendChild(b);c=e.Bd;if(10===c||11===c||12===c||13===c||14===c)if(g.ug(b,"text-emphasis-style","filled circle"),g.ug(b,"text-emphasis-color","currentcolor"),g.ug(b,"webkit-text-emphasis","filled circle"),11===e.Bd||13===e.Bd)g.ug(b,"webkit-text-emphasis-position","under left"),g.ug(b,"text-emphasis-position","under left");c=!0;if(4===e.Bd||7===e.Bd||12===e.Bd||
14===e.Bd)g.ug(h,"ruby-position","over"),g.ug(h,"-webkit-ruby-position","before");else if(5===e.Bd||6===e.Bd||11===e.Bd||13===e.Bd)g.ug(h,"ruby-position","under"),g.ug(h,"-webkit-ruby-position","after"),c=!1;e=f?g.He("DIV"):g.He("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.ug(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.ug(f,"display","none"),f=f.nextElementSibling,g.ug(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.ug(h.lastElementChild,"display","none"),d?(g.ug(h,"padding-top","0.6em"),g.ug(f,"top","0")):(g.ug(h,"padding-bottom","0.6em"),g.ug(f,"bottom","0")));return h},h2=function(){g.B.apply(this,arguments)},i2=function(a){h2.call(this);
this.I=a;this.D={};this.U={};this.W={};this.F="_"+g2++;this.L={};this.B=this.u=null;this.K=!0},j2=function(a,b){var c=a.getAttribute(b);
if(null!=c)return Number(c)},k2=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"===c},l2=function(a,b){var c=j2(a,b);
return void 0!==c?c:null},n2=function(a,b){var c=a.getAttribute(b);
if(null!=c)return m2.test(c),c},tFa=function(a,b){var c={},d=b.getAttribute("ws");
g.Sa(c,d?a.W[d]:a.I);d=l2(b,"mh");null!=d&&(c.pp=d);d=l2(b,"ju");null!=d&&(c.textAlign=d);d=l2(b,"pd");null!=d&&(c.Ve=d);d=l2(b,"sd");null!=d&&(c.GA=d);d=n2(b,"wfc");null!=d&&(c.windowColor=d);d=j2(b,"wfo");void 0!==d&&(c.windowOpacity=d/255);return c},uFa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Sa(c,a.U[d]);d=l2(b,"ap");null!=d&&(c.Wh=d);d=j2(b,"cc");null!=d&&(c.kl=d);d=j2(b,"ah");null!=d&&(c.Wg=d);d=j2(b,"rc");null!=d&&(c.Lk=d);d=j2(b,"av");null!=d&&(c.Ii=d);return c},vFa=function(a,b,c,d){var e={};
g.Sa(e,uFa(a,b));g.Sa(e,tFa(a,b));d?g.Ub(e,a.I)?(d=a.F,e=a.I):d="_"+g2++:d=b.getAttribute("id")||"_"+g2++;a=j2(b,"t")+c;b=j2(b,"d")||0x8000000000000;if(2===e.Ve||3===e.Ve)c=e.Lk,e.Lk=e.kl,e.kl=c;return new f2(a,b,0,d,e)},o2=function(a){h2.call(this);
this.I=a;this.u=new Map;this.D=new Map;this.F=new Map;this.B=new Map},p2=function(a){a=g.de(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},wFa=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.D.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.F.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.Lk=a);b=b.ccColCount;void 0!==b&&(f.kl=b);if(2===f.Ve||3===f.Ve)b=f.Lk,f.Lk=f.kl,f.kl=b;return new f2(c,d,0,e,f)},r2=function(){this.C=this.time=this.mode=this.B=0;
this.D=new q2(this);this.F=new q2(this);this.u=[];this.clear()},yFa=function(a,b,c){if(255===a&&255===b||!a&&!b)return{Um:a,
dl:b,result:0};a=xFa[a];b=xFa[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.dl===d;if(d)return{Um:a,dl:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Um:a,dl:b,result:2};return{Um:a,dl:b,result:3}},AFa=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.C&&a.reset(),a.D.u.clear(),a.F.u.clear()):(a.C=0,zFa(a.D,b,c,d))},BFa=function(a,b){a.u.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.q(a.u),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?AFa(a,d.hC,d.iC,b):1===d.type&&a.B&496&&zFa(a.F,d.hC,d.iC,b);a.u.length=0},s2=function(){this.type=0},t2=function(){this.state=this.dl=this.Um=0},CFa=function(){this.timestamp=this.u=0},u2=function(a){this.F=a;
this.C=[];this.u=this.B=this.row=0;this.style=new s2;for(a=this.D=0;15>=a;a++){this.C[a]=[];for(var b=0;32>=b;b++)this.C[a][b]=new CFa}},v2=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.F.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.C[m][p];
if(0!==r.u){0===c&&(c=m,d=p);n=String.fromCharCode(r.u);var t=r.timestamp;t<e&&(e=t);r.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===r.u||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.D(c,d,e,l,f)}else for(d=c=0,f=e=a.F.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.C[h][m],r=p.u,0!==r&&(0===c&&(c=h,d=m),n=String.fromCharCode(r),t=p.timestamp,t<=e&&(e=t),l+=n,p.reset()),32===m||0===r)l&&b.D(c,d,e,f,l),e=f,l="",d=c=0},HFa=function(a,b){switch(a){case 0:return DFa[(b&127)-32];
case 1:return EFa[b&15];case 2:return FFa[b&31];case 3:return GFa[b&31]}return 0},w2=function(a){return a.C[a.row][a.B]},x2=function(a,b,c){2<=b&&1<a.B&&(--a.B,w2(a).u=0);
var d=w2(a);d.timestamp=a.F.time+0;d.u=HFa(b,c);32>a.B&&a.B++},IFa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.C[b+e][f],l=a.C[c+e][f];
h.u=l.u;h.timestamp=l.timestamp}},y2=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.C[b+d][e].reset()},z2=function(a){a.row=0<a.u?a.u:1;
a.B=1;y2(a,0,15)},A2=function(a){this.C=a;
this.F=0;this.style=new s2;this.I=new u2(this.C);this.K=new u2(this.C);this.text=new u2(this.C);this.B=this.I;this.D=this.K;this.u=this.B},B2=function(a,b,c){var d=a.B,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.u||(v2(d,c),z2(a.B),z2(a.D),d.row=15,d.u=b,e=!0)}a.style.set(3);a.u=d;a.u.style=a.style;a.C.mode=1<<d.D;e?d.B=1:d.u!==b&&(d.u>b?(v2(d,c),y2(d,d.row-d.u,b)):d.row<b&&(b=d.u),d.u=b)},JFa=function(a){a.style.set(1);
a.u=a.D;a.u.u=0;a.u.style=a.style;a.C.mode=1<<a.u.D},KFa=function(a){a.style.set(4);
a.u=a.text;a.u.style=a.style;a.C.mode=1<<a.u.D},q2=function(a){this.B=a;
this.F=0;this.C=new A2(this.B);this.I=new A2(this.B);this.u=new t2;this.D=this.C},zFa=function(a,b,c,d){a.u.update();
b=yFa(b,c,a.u);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Um;c=b.dl;if(32<=e||!e)a.B.mode&a.B.B&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.D.u,b&96&&x2(a,0,b),c&96&&x2(a,0,c),0!==b&&0!==c&&3===a.style.type&&v2(a,d));else if(e&16)a:if(!a.u.matches(e,c)&&(b=a.u,b.Um=e,b.dl=c,b.state=2,b=e&8?a.I:a.C,a.D=b,a.B.mode=1<<(a.F<<2)+(b.F<<1)+(4===b.style.type?1:0),(a.B.mode|1<<(a.F<<2)+(b.F<<1)+(4!==b.style.type?1:0))&a.B.B))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.u;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.u&&(d=c.u,d===c.row))break;var f=1+c.row-c.u,h=1+d-c.u;IFa(c,h,f,c.u);b=f;e=c.u;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));y2(c,b,e)}}c.row=d;c.B=a+1}else switch(e&7){case 1:switch(c&112){case 32:x2(b.u,0,32);break a;case 48:57===c?(d=b.u,w2(d).u=0,32>d.B&&d.B++):x2(b.u,1,c&15)}break;case 2:c&32&&x2(b.u,2,c&31);break;case 3:c&32&&x2(b.u,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:JFa(b);
break;case 33:d=b.u;1<d.B&&(--d.B,w2(d).u=0);break;case 36:d=b.u;b=w2(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.C[a][c]===b){for(;32>=c;c++)d.C[a][c].reset();break}break;case 37:B2(b,2,d);break;case 38:B2(b,3,d);break;case 39:B2(b,4,d);break;case 40:x2(b.u,0,32);break;case 41:b.style.set(2);b.u=b.B;b.u.u=0;b.u.style=b.style;b.C.mode=1<<b.u.D;break;case 42:d=b.text;d.u=15;d.style.set(4);z2(d);KFa(b);break;case 43:KFa(b);break;case 44:a=b.B;switch(b.style.get()){case 1:case 2:case 3:v2(a,d)}y2(a,
0,15);break;case 45:b:{a=b.u;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.B=1;break b}case 3:}2>a.u&&(a.u=2,a.row<a.u&&(a.row=a.u));b=a.row-a.u+1;v2(a,d);IFa(a,b,b+1,a.u-1);y2(a,a.row,1)}break;case 46:y2(b.D,0,15);break;case 47:v2(b.B,d),b.D.updateTime(b.C.time+0),d=b.D,b.D=b.B,b.B=d,JFa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.u,32<(d.B+=c&3)&&(d.B=32)}}},LFa=function(){},C2=function(a,b,c){this.K=a;
this.I=c;this.version=this.F=this.C=this.byteOffset=0;this.u=new DataView(this.K);this.B=[]},D2=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.u.getUint8(b)},E2=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.u.getUint32(b)},F2=function(a,b){h2.call(this);
this.B=a;this.D=b;this.track="CC3"===this.D.languageName?4:0;this.u=new r2;this.u.B=1<<this.track},G2=function(a){if("string"===typeof a)return!1;
a=new C2(a,8,0);return MFa(a)},MFa=function(a){if(!(a.byteOffset<a.u.byteLength)||1380139777!==E2(a))return!1;
a.version=D2(a);if(1<a.version)return!1;D2(a);D2(a);D2(a);return!0},H2=function(){h2.call(this)},NFa=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.ii=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new e2(b,c,d,e.id,p.nodeValue,f||0<n,g.Sb(l)?void 0:l),m.push(p),e.u.push(p);else{var r={};g.Sa(r,l);NFa(a,b,c,d,e,!0,p,r,m)}}},I2=function(a){var b=a.split(":");
a=0;b=g.q(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},OFa=function(a,b,c,d){d=Object.assign({pp:0},d);
return new f2(a,b,c,"_"+g2++,d)},J2=function(a){g.B.call(this);
this.B=a;this.u=null},QFa=function(a){var b={};
if(a=T1(a))b.lang=a,PFa.test(a)&&(b.Ve=1);return b},M2=function(a){g.zO.call(this,a);
var b=this;this.J=a;this.B=this.J.S();this.videoData=this.J.getVideoData();this.Oa=this.J.Ja();this.D={Jc:{}};this.F={Jc:{}};this.W=[];this.U={};this.la={};this.da=!1;this.Fa=g.Opa(this.videoData,this.J);this.Ua=!!this.videoData.captionTracks.length;this.Xa=!!this.videoData.qg;this.Ha="3"===this.B.controlsType;this.C=this.K=this.L=this.ka=this.Aa=null;this.ya=new J2(this.B);this.u=null;this.ga=new g.pO(this);var c=null,d=g.oo("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.Qn(d));this.storage=
c;c=a.fd();d=!(!c||!c.Ns());this.Ia=!(!c||!c.Os());this.I=this.Ha&&d&&!this.Fa;this.aa=!this.I&&this.Ha&&this.Ia&&this.Fa;g.C(this,this.ya);this.I?this.ea=this.X=null:(this.X=new g.mn(this.MH,void 0,this),g.C(this,this.X),this.ea=new g.D(this.QQ,2E3,this),g.C(this,this.ea));g.C(this,this.ga);this.I||this.ga.P(a,"resize",this.YA);this.ga.P(a,"onPlaybackAudioChange",this.GN);this.ga.P(a,g.IG("captions"),function(e){b.zd(e)});
this.ga.P(a,g.JG("captions"),function(e){b.rf(e)});
K2(this,L2(this,"display-settings")||{})},RFa=function(a){if(1===a.B.Ia||1===a.videoData.xw||"alwayson"===g.TI(a.videoData,"yt:cc"))return!0;
if(2===a.B.Ia){var b;g.qE(a.B)?b=(0,g.VCa)():b=L2(a,"module-enabled");if(null!=b)return!!b}if(a.videoData.captionTracks.length)var c=a.player.getAudioTrack().C;return"ON"===c||"on"===g.TI(a.videoData,"yt:cc")},N2=function(a,b){if(a.u&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.B||"FORCED_ON"===c.C},SFa=function(a){var b=!1,c=g.Dt(g.Bt.getInstance(),65);
if(g.qE(a.B)&&null!=c){if(null!=(0,g.VCa)())return!1;b=!c}return b},P2=function(a,b){if(a.C){if(a.K&&a.K.F)return a.K.F;
var c=b;c||(c=a.Xa?!1:a.Ua?!1:!0);c=U1(a.C.B,c);for(var d=[a.videoData.captionsLanguagePreference,a.B.captionsLanguagePreference,g.TI(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(T1(c[f])===d[e])return c[f];return a.K&&a.K.D?a.K.D:(d=c.find(function(h){return h.isDefault}))?d:c[0]||O2(a)}return null},O2=function(a){return a.K&&a.K.B},Q2=function(a){var b=O2(a);
return!!b&&a.u===b},TFa=function(a,b){for(var c=a.J.fd().Zd().textTracks,d=a.u.toString(),e=0;e<c.length;e++){var f=c[e];
f.id===d&&(b?"showing"!==f.mode&&(f.mode="showing"):"showing"===f.mode&&(f.mode="disabled"))}},S2=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.da=c,a.da&&(g.qE(a.B)?(0,g.Z_)(!!b):R2(a,"module-enabled",!!b)));a.u=b;N2(a)&&(a.u=O2(a));a.load()},UFa=function(a,b){var c=a.Oa.getVideoContentRect(!0).height;
if(!c)return null;var d=a.u?a.u.languageCode:null;!b.params.Ve&&d&&PFa.test(d)&&(b.params.Ve=1);d=a.Oa.getPlayerSize();switch(null!=b.params.pp?b.params.pp:1<b.u.length?1:0){case 1:return new c2(b,a.D,a.F,c,d.width,d.height,a.B.experiments);case 2:return new d2(b,a.D,a.F,c,d.width,d.height,a.B.experiments);default:return new b2(b,a.D,a.F,c,d.width,d.height,a.B.experiments)}},K2=function(a,b,c){c=void 0===c?!1:c;
var d=T2.Jc;a.D={};g.Sa(a.D,T2);a.D.Jc={};g.Sa(a.D.Jc,d);a.F={Jc:{}};var e=b.backgroundOverride?a.F:a.D,f=b.background||d.background;m2.test(f);e.Jc.background=f;e=b.colorOverride?a.F:a.D;f=b.color||d.color;m2.test(f);e.Jc.color=f;e=b.windowColorOverride?a.F:a.D;f=b.windowColor||T2.windowColor;m2.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.F:a.D;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Jc.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.F:a.D;f=b.fontSizeIncrement;null==
f&&(f=d.fontSizeIncrement);e.Jc.fontSizeIncrement=f;f=b.fontStyleOverride?a.F:a.D;e=b.fontStyle;null==e&&(e=d.bold&&d.ii?3:d.bold?1:d.ii?2:0);f=f.Jc;switch(e){case 1:f.bold=!0;delete f.ii;break;case 2:delete f.bold;f.ii=!0;break;case 3:f.bold=!0;f.ii=!0;break;default:delete f.bold,delete f.ii}e=b.textOpacityOverride?a.F:a.D;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Jc.textOpacity=f;e=b.windowOpacityOverride?a.F:a.D;f=b.windowOpacity;null==f&&(f=T2.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.F:a.D;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Jc.charEdgeStyle=f;e=b.fontFamilyOverride?a.F:a.D;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Jc.fontFamily=f;a.loaded&&a.YA();c&&R2(a,"display-settings",b)},WFa=function(a,b){if(b&&!a.L){var c=qFa({Ve:0,
lang:"en"});a.L=[c,new e2(c.start,c.end-c.start,0,c.id,"Captions look like this")];a.player.Kd(a.L)}else!b&&a.L&&(VFa(a,a.L),a.L=null)},VFa=function(a,b){a.player.Pf(b);
g.Cb(b,function(c){g.lb(this.W,c)},a);
g.nn(a.X)},L2=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},R2=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}};
g.NO.prototype.zq=g.ca(19,function(){this.Z();for(var a=g.se(document,"track",void 0,this.u),b=0;b<a.length;b++)g.Le(a[b])});
g.OS.prototype.zq=g.ca(18,function(){this.u.zq()});
g.NO.prototype.Os=g.ca(17,function(){return!(!this.u.textTracks||!this.u.textTracks.addEventListener)});
g.OS.prototype.Os=g.ca(16,function(){return this.u.Os()});
g.NO.prototype.Ns=g.ca(15,function(){return!!this.u.textTracks});
g.OS.prototype.Ns=g.ca(14,function(){return this.u.Ns()});
g.NO.prototype.nq=g.ca(13,function(a){this.Z();for(var b=0;b<a.length;b++)this.u.appendChild(a[b])});
g.OS.prototype.nq=g.ca(12,function(a){this.u.nq(a)});
g.Vx.prototype.Zt=g.ca(1,function(){return 0});
g.aA.prototype.Zt=g.ca(0,function(a){return(a=this.Yh(a))?a.u:0});
var PFa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;g.u(W1,g.B);R1=W1.prototype;R1.yu=function(){};
R1.zu=function(){};
R1.Tk=function(){};
R1.So=function(){return""};
R1.EG=function(){return!1};
R1.ca=function(){this.Tk();g.B.prototype.ca.call(this)};
g.u(X1,W1);X1.prototype.yu=function(a,b,c){var d=this;this.ma();b=this.So(a,b);this.Tk();this.u=g.xq(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})};
X1.prototype.zu=function(a){if(this.audioTrack)for(var b=g.q(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())V1(this.B,c.value);a()};
X1.prototype.So=function(a,b){var c=a.url,d={fmt:b};if("srv3"===b||"3"===b||"json3"===b)g.Zq()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.translationLanguage&&(d.tlang=T1(a));return g.hq(c,d)};
X1.prototype.Tk=function(){this.u&&this.u.abort()};
Y1.prototype.contains=function(a){a=g.xb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
Y1.prototype.length=function(){return this.segments.length/2};
g.u(Z1,g.B);R1=Z1.prototype;R1.ca=function(){g.B.prototype.ca.call(this);this.B&&this.B.cancel()};
R1.QE=function(){this.seekTo(this.player.getCurrentTime())};
R1.seekTo=function(a){a-=this.player.Ac();var b=this.u;this.u=g.bb(this.W.Bl(a).u);b!==this.u&&this.L&&this.L()};
R1.reset=function(){this.D=new Y1;this.B&&(this.B.cancel(),this.B=null)};
R1.nE=function(){this.ma();var a;if(a=null!=this.u)a=this.u,a=a.u.Sl(a);!a||this.B||this.u&&30<this.u.startTime-this.player.getCurrentTime()||(a=this.u,a=a.u.Kr(a),a.u[0].duration?(this.D.contains(a.u[0].xa)||dFa(this,a),this.u=g.bb(a.u)):!g.P(this.U.experiments,"force_caption_seek_for_live_killswitch")&&this.u&&this.u.D&&this.u.D+this.player.Ac()<this.player.getCurrentTime()&&this.seekTo(this.player.getCurrentTime()));this.K.start()};
g.u($1,W1);R1=$1.prototype;R1.yu=function(a,b,c){var d=this;this.Tk();b=fFa(this,a.getId());b||(b=a.languageCode,b=this.u.isManifestless?gFa(this,b,"386"):gFa(this,b));if(b){var e=1E3*(b.index.Zt(b.index.bi())-b.index.kf(b.index.bi()));this.C=new Z1(new g.Aw,this.J,b,function(f,h){c(f,a,h,e)},this.I||g.qw(b.info),function(){d.C&&d.C.reset();
d.D=!0})}};
R1.EG=function(){var a=this.D;this.D=!1;return a};
R1.zu=function(a){var b=this.I?[new g.OH({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.OH({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.u.isManifestless?eFa(this,"386"):eFa(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())V1(this.B,c.value);a()};
R1.Tk=function(){this.C&&(this.C.dispose(),this.C=null)};
R1.So=function(){return""};
g.u(a2,W1);a2.prototype.yu=function(a,b,c){var d=this;this.ma();b=this.So(a,b);this.Tk();this.u=g.xq(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})};
a2.prototype.zu=function(a){var b=this,c=this.C,d={type:"list",tlangs:1,v:this.videoId,vssids:1};this.MD&&(d.asrs=1);c=g.hq(c,d);this.Tk();this.u=g.xq(c,{format:"RAW",onSuccess:function(e){b.u=null;if((e=e.responseXML)&&e.firstChild){for(var f=e.getElementsByTagName("track"),h=0;h<f.length;h++){var l=f[h],m=l.getAttribute("lang_code"),n=l.getAttribute("lang_translated"),p=l.getAttribute("name"),r=l.getAttribute("kind"),t=l.getAttribute("id"),v="true"===l.getAttribute("lang_default"),x="true"===l.getAttribute("cantran");
l=l.getAttribute("vss_id");V1(b.B,new g.OH({languageCode:m,languageName:n,name:p,kind:r,id:t,is_servable:!0,is_translateable:x,vss_id:l,is_default:v}))}e=e.getElementsByTagName("target");f=e.length;for(h=0;h<f;h++)m={languageCode:e[h].getAttribute("lang_code"),languageName:e[h].getAttribute("lang_translated"),languageOriginal:e[h].getAttribute("lang_original"),id:e[h].getAttribute("id"),isDefault:"true"===e[h].getAttribute("lang_default")},b.D[m.languageCode]=m.languageName,b.F.push(m)}a()},
withCredentials:!0})};
a2.prototype.So=function(a,b){var c=this.C,d={v:this.videoId,type:"track",lang:a.languageCode,name:a.getName(),kind:a.kind,fmt:b};a.translationLanguage&&(d.tlang=T1(a));return c=g.hq(c,d)};
a2.prototype.Tk=function(){this.u&&this.u.abort()};
var m2=/^#(?:[0-9a-f]{3}){1,2}$/i;var iFa=["left","right","center","justify"];g.u(b2,g.U);R1=b2.prototype;R1.UL=function(a,b){var c=g.Ig(this.element,this.element.parentElement);this.Aa=a-c.x;this.Fa=b-c.y;g.G(this.element,"ytp-dragging")};
R1.TL=function(a,b){var c=g.Kg(this.element),d=a-this.Aa-.02*this.playerWidth,e=b-this.Fa-.02*this.playerHeight,f=(d+c.width/2)/this.maxWidth*3;f=Math.floor(g.de(f,0,2));var h=(e+c.height/2)/this.Ia*3;h=Math.floor(g.de(h,0,2));var l=f+3*h;d=(d+f/2*c.width)/this.maxWidth;d=100*g.de(d,0,1);c=(e+h/2*c.height)/this.Ia;c=100*g.de(c,0,1);this.B.params.Wh=l;this.B.params.Ii=c;this.B.params.Wg=d;this.u.Wh=l;this.u.Ii=c;this.u.Wg=d;this.cH()};
R1.SL=function(){g.yn(this.element,"ytp-dragging")};
R1.cH=function(){this.Vp(this.F)};
R1.Hb=function(){return this.type};
R1.Vp=function(a){var b=Math.min(this.gD(),this.maxWidth),c=this.fD(),d="";3===this.B.params.Ve&&(d="rotate(180deg)");g.ug(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Zw(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.u.Wg+2;d=this.u.Wh;switch(d){case 0:case 3:case 6:b=this.u.Jc.fontSizeIncrement;!g.P(this.experiments,"web_player_ignore_left_percentage_for_large_font_killswitch")&&
b&&2<b&&2!==this.u.Ve&&3!==this.u.Ve&&(e=2);a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.D.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.u.Ii+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-
b+"%"}g.ug(this.element,a)};
R1.Zw=function(a){var b;for(b=0;b<a.length&&a[b]===this.F[b];b++);if(this.aa||this.F.length>b)b=0,this.aa=!1,this.F=[],this.I=this.ga=this.da=null,g.Je(this.D);for(;b<a.length;b++)mFa(this,a[b])};
R1.gD=function(){return 0};
R1.fD=function(){return 0};
R1.toString=function(){return g.U.prototype.toString.call(this)};g.u(c2,b2);c2.prototype.Zw=function(a){var b=this.B.u;b2.prototype.Zw.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.u===e)var d=f;else{d={};g.Sa(d,c.u);g.Sa(d,XFa);var e=c.u;var f=d}mFa(this,c,d)}};
var XFa={AK:!0};g.u(d2,b2);R1=d2.prototype;R1.cH=function(){g.rn(this.la)};
R1.xP=function(){g.yn(this.element,"ytp-rollup-mode");this.Vp(this.Xa,!0)};
R1.fD=function(){return this.C?this.W:this.L};
R1.gD=function(){return this.C?this.L:this.W};
R1.Vp=function(a,b){this.Xa=a;if(this.B.params.Lk){for(var c=0,d=0;d<this.F.length&&c<a.length;d++)this.F[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.F.concat(a.slice(c)));this.Oa=this.W;this.L=this.W=0;b2.prototype.Vp.call(this,a);pFa(this,b)}b2.prototype.Vp.call(this,a)};g.u(e2,g.FG);e2.prototype.toString=function(){return g.FG.prototype.toString.call(this)};g.u(f2,g.FG);f2.prototype.toString=function(){return g.FG.prototype.toString.call(this)};
var g2=0;g.u(h2,g.B);h2.prototype.C=function(){return[]};
h2.prototype.reset=function(){};g.u(i2,h2);i2.prototype.reset=function(){this.L={};this.B=this.u=null;this.K=!0};
i2.prototype.C=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var h=this.D,l={},m=c.getAttribute("p");m&&g.Sa(l,this.D[m]);m=k2(c,"b");null!=m&&
(l.bold=m);m=k2(c,"i");null!=m&&(l.ii=m);m=k2(c,"u");null!=m&&(l.underline=m);m=l2(c,"et");null!=m&&(l.charEdgeStyle=m);m=l2(c,"of");null!=m&&(l.offset=m);m=n2(c,"bc");null!=m&&(l.background=m);m=n2(c,"ec");null!=m&&(l.mx=m);m=n2(c,"fc");null!=m&&(l.color=m);m=l2(c,"fs");null!=m&&0!==m&&(l.fontFamily=m);m=j2(c,"sz");void 0!==m&&(l.fontSizeIncrement=m/100-1);m=j2(c,"bo");void 0!==m&&(l.backgroundOpacity=m/255);m=j2(c,"fo");void 0!==m&&(l.textOpacity=m/255);m=l2(c,"rb");null!=m&&10!==m&&0!==m&&(l.Bd=
10<m?m-1:m);c=l2(c,"hg");null!=c&&(l.HD=c);h[d]=l;break;case "ws":d=c.getAttribute("id");this.W[d]=tFa(this,c);break;case "wp":d=c.getAttribute("id"),this.U[d]=uFa(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "w":this.u=vFa(this,d,e,!1);(d=this.L[this.u.id])&&d.end>this.u.start&&(d.end=this.u.start);this.L[this.u.id]=this.u;c.push(this.u);break;case "p":var n=e;h=[];l=d.getAttribute("w")||this.F;m=!!k2(d,
"a");n=(j2(d,"t")||0)+n;var p=j2(d,"d")||5E3;m||(!this.K&&this.B&&this.B.windowId===l&&this.B.end>n&&(this.B.end=n),this.B&&"\n"===this.B.text&&(this.B.text=""));var r=m?6:5,t=d.getAttribute("p");t=t?this.D[t]:null;var v=Array.from(d.childNodes);v.length&&(this.K=null!=d.getAttribute("d"));for(var x=0;x<v.length;x++){var y=v[x],F=void 0;0<x&&(m=!0);var E=void 0;1===y.nodeType&&(E=y);if(E&&"s"===E.tagName){if((y=(y=E.getAttribute("p"))?this.D[y]:null)&&y.Bd&&(1===y.Bd?(y=v.slice(x,x+4),4===y.length&&
(F=sFa(n,p,l,m,r,y,this.D),x+=3)):F=sFa(n,p,l,m,r,[E],this.D)),!F){var H=E;F=n;E=p;y=l;var I=m,J=r,Ea=H.textContent?H.textContent:"",la=H.getAttribute("p");la=la?this.D[la]:null;H=j2(H,"t")||0;F=new e2(F+H,E-H,J,y,Ea,I,la)}}else F=new e2(n,p,r,l,y.textContent||"",m,t);h.push(F);this.B=F}if(0<h.length)for(h[0].windowId===this.F&&(this.u=vFa(this,d,e,!0),c.push(this.u)),d=g.q(h),h=d.next();!h.done;h=d.next())h=h.value,h.windowId=this.u.id,this.u.u.push(h),c.push(h)}e=c}else e=[];return e};var YFa=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.u(o2,h2);o2.prototype.reset=function(){this.B.clear()};
o2.prototype.C=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens)for(var d=0,e=g.q(c.pens),f=e.next();!f.done;f=e.next()){f=f.value;var h={},l=f.pParentId;l&&Object.assign(h,this.u.get(l));f.bAttr&&(h.bold=!0);f.iAttr&&(h.ii=!0);f.uAttr&&(h.underline=!0);l=f.ofOffset;null!=l&&(h.offset=l);void 0!==f.szPenSize&&(h.fontSizeIncrement=f.szPenSize/100-1);l=f.etEdgeType;null!=l&&(h.charEdgeStyle=l);void 0!==f.ecEdgeColor&&(h.mx=p2(f.ecEdgeColor));l=f.fsFontStyle;null!=l&&0!==l&&(h.fontFamily=l);
void 0!==f.fcForeColor&&(h.color=p2(f.fcForeColor));void 0!==f.foForeAlpha&&(h.textOpacity=f.foForeAlpha/255);void 0!==f.bcBackColor&&(h.background=p2(f.bcBackColor));void 0!==f.boBackAlpha&&(h.backgroundOpacity=f.boBackAlpha/255);(l=f.rbRuby)&&10!==l&&(h.Bd=10<l?l-1:l,h.Gi=YFa.get(h.Bd));f.hgHorizGroup&&(h.HD=f.hgHorizGroup);this.u.set(d++,h)}if(c.wsWinStyles)for(d=0,e=g.q(c.wsWinStyles),f=e.next();!f.done;f=e.next())f=f.value,h={},(l=f.wsParentId)?Object.assign(h,this.F.get(l)):Object.assign(h,
this.I),void 0!==f.mhModeHint&&(h.pp=f.mhModeHint),void 0!==f.juJustifCode&&(h.textAlign=f.juJustifCode),void 0!==f.pdPrintDir&&(h.Ve=f.pdPrintDir),void 0!==f.sdScrollDir&&(h.GA=f.sdScrollDir),void 0!==f.wfcWinFillColor&&(h.windowColor=p2(f.wfcWinFillColor)),void 0!==f.wfoWinFillAlpha&&(h.windowOpacity=f.wfoWinFillAlpha/255),this.F.set(d++,h);if(c.wpWinPositions)for(d=0,e=g.q(c.wpWinPositions),f=e.next();!f.done;f=e.next())f=f.value,h={},(l=f.wpParentId)&&Object.assign(h,this.D.get(l)),void 0!==f.ahHorPos&&
(h.Wg=f.ahHorPos),void 0!==f.apPoint&&(h.Wh=f.apPoint),void 0!==f.avVerPos&&(h.Ii=f.avVerPos),void 0!==f.ccCols&&(h.kl=f.ccCols),void 0!==f.rcRows&&(h.Lk=f.rcRows),this.D.set(d++,h);if(c.events)for(d=[],c=g.q(c.events),e=c.next();!e.done;e=c.next()){var m=e.value;e=(m.tStartMs||0)+b;f=m.dDurationMs||0;if(m.id)h=String(m.id),e=wFa(this,m,e,f,h),d.push(e),this.B.set(h,e);else{m.wWinId?h=m.wWinId.toString():(h="_"+g2++,l=wFa(this,m,e,f,h),d.push(l),this.B.set(h,l));0===f&&(f=5E3);l=this.B.get(h);var n=
!!m.aAppend,p=n?6:5,r=m.segs,t=null;m.pPenId&&(t=this.u.get(m.pPenId));for(m=0;m<r.length;m++){var v=r[m],x=v.utf8;if(x){var y=v.tOffsetMs||0,F=null;v.pPenId&&(F=this.u.get(v.pPenId));if(2===(null!=l.params.pp?l.params.pp:1<l.u.length?1:0)&&n&&"\n"===x)continue;if(v=F&&1===F.Bd)if(v=m,v+3>=r.length||!r[v+1].pPenId||!r[v+2].pPenId||!r[v+3].pPenId)v=!1;else{var E=r[v+1].pPenId;(E=this.u.get(E))&&E.Bd&&2===E.Bd?(E=r[v+2].pPenId,E=this.u.get(E),!E||!E.Bd||3>E.Bd?v=!1:(E=r[v+3].pPenId,v=(E=this.u.get(E))&&
E.Bd&&2===E.Bd?!0:!1)):v=!1}if(v){y=r[m+1].utf8;v=r[m+3].utf8;E=r[m+2].utf8;var H=this.u.get(r[m+2].pPenId);x=rFa(x,y,E,v,H);n=new e2(e,f,p,h,x,n,F);m+=3}else n=new e2(e+y,f-y,p,l.id,x,n,F||t);n&&(d.push(n),l.u.push(n))}n=!0}}}else d=[];return d};r2.prototype.clear=function(){this.C=this.time=this.mode=0;this.u=[];this.reset()};
r2.prototype.reset=function(){this.mode=0;this.D.reset(0);this.F.reset(1)};
var xFa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];s2.prototype.set=function(a){this.type=a};
s2.prototype.get=function(){return this.type};
t2.prototype.clear=function(){this.state=0};
t2.prototype.update=function(){this.state=2===this.state?1:0};
t2.prototype.isValid=function(){return 0!==this.state};
t2.prototype.matches=function(a,b){return this.isValid()&&a===this.Um&&b===this.dl};
CFa.prototype.reset=function(){this.timestamp=this.u=0};
u2.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.C[b][c].timestamp=a};
u2.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.C[b][c];a=0===d.u?a+"_":a+String.fromCharCode(d.u)}a+="\n"}return a};
u2.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.C[b][c].reset();this.D=a;this.u=0;this.B=this.row=1};
var DFa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],EFa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],FFa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],GFa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];A2.prototype.reset=function(a,b){this.F=b;this.style.set(2);this.B=this.I;this.D=this.K;this.u=this.B;var c=(a<<2)+(b<<1);this.I.reset(c);this.K.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
q2.prototype.reset=function(a){this.F=a;this.u.clear();this.D=this.C;this.C.reset(a,0);this.I.reset(a,1)};LFa.prototype.D=function(){};g.u(C2,LFa);C2.prototype.D=function(a,b,c,d,e){if(c<d){var f="_"+g2++;c=c/1E3-this.I;d=d/1E3-this.I;a=new f2(c,d-c,5,f,{textAlign:0,Wh:0,Wg:2.5*b,Ii:5.33*a});e=new e2(c,d-c,5,f,e);this.B.push(a);this.B.push(e)}};
g.u(F2,h2);F2.prototype.C=function(a){a=new C2(a,a.byteLength,this.B);if(MFa(a)){for(;a.byteOffset<a.u.byteLength;)for(0===a.version?a.C=E2(a)*(1E3/45):1===a.version&&(a.C=4294967296*E2(a)+E2(a)),a.F=D2(a);0<a.F;a.F--){var b=D2(a),c=D2(a),d=D2(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.u,b.u.push({time:a.C,type:this.track,hC:c,iC:d,order:b.u.length}))}BFa(this.u,a);return a.B}return[]};
F2.prototype.reset=function(){this.u.clear()};g.u(H2,h2);
H2.prototype.C=function(a,b){for(var c=[],d=a.split(ZFa),e=1;e<d.length;e++){var f=d[e],h=b;if(""!==f&&!$Fa.test(f)){var l=U2.exec(f);if(l&&4<=l.length){var m=I2(l[1]),n=I2(l[2])-m;m+=h;var p=(l=l[3])?l.split(" "):[];l={};var r=null,t="",v=null,x="";l.textAlign=2;p=g.q(p);for(var y=p.next();!y.done;y=p.next())if(y=y.value.split(":"),2===y.length){var F=y[1];switch(y[0]){case "line":y=F.split(",");y[0].endsWith("%")&&(r=y[0],l.Ii=Number.parseInt(r,10),2===y.length&&(t=y[1].trim()));break;case "position":y=
F.split(",");v=y[0];l.Wg=Number.parseInt(v,10);2===y.length&&(x=y[1].trim());break;case "align":switch(F){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}r||(l.Ii=100,t||(t="end"));if(!v)switch(l.textAlign){case 0:l.Wg=0;break;case 1:l.Wg=100;break;default:l.Wg=50}r=0;switch(t){case "center":r+=3;break;case "end":r+=6;break;default:r+=0}switch(x){case "line-left":r+=0;break;case "center":r+=1;break;case "line-right":r+=2;break;default:switch(l.textAlign){case 0:r+=
0;break;case 2:r+=1;break;case 1:r+=2}}l.Wh=0>r||8<r?7:r;f=f.substring(U2.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");x=l;l=f;f={};if(0>l.indexOf("<")&&0>l.indexOf("&"))h=OFa(m,n,5,x),n=new e2(m,n,5,h.id,l,!1,g.Sb(f)?void 0:f),c.push(h),c.push(n),h.u.push(n);else for(t=l.split(aGa),1===t.length?(l=5,x=OFa(m,n,l,x)):(r=l=6,x=Object.assign({kl:32},x),x=new f2(m,n,r,"_"+g2++,x)),c.push(x),r=m,v=0;v<t.length;v++)p=t[v],0===v%2?(y=g.A_("<html>"+p+"</html>"),y.getElementsByTagName("parsererror").length?
(F=y.createElement("span"),F.appendChild(y.createTextNode(p))):F=y.firstChild,NFa(this,r,n-(r-m),l,x,0<v,F,f,c)):r=I2(p)+h}U2.lastIndex=0}}return c};
var $Fa=/^NOTE/,ZFa=/(?:\r\n|\r|\n){2,}/,U2=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),aGa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.u(J2,g.B);J2.prototype.clear=function(){this.u&&this.u.dispose();this.u=null};
J2.prototype.reset=function(){this.u&&this.u.reset()};
J2.prototype.ca=function(){g.B.prototype.ca.call(this);this.clear()};var T2={windowColor:"#080808",windowOpacity:0,textAlign:2,Wh:7,Wg:50,Ii:100,Jc:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.u(M2,g.zO);R1=M2.prototype;R1.ca=function(){if(this.I||this.aa){var a=this.J.fd();a&&!a.ma()&&a.zq()}else WFa(this,!1);g.zO.prototype.ca.call(this)};
R1.Qn=function(){return this.Ha?this.I||this.aa:SFa(this)||N2(this)?!0:RFa(this)};
R1.load=function(){var a=this;g.zO.prototype.load.call(this);var b=!g.P(this.B.experiments,"web_player_captions_track_list_changed_killswitch");this.K=this.player.getAudioTrack();if(this.C)this.u&&(this.ya.clear(),this.I?TFa(this,!0):3!==this.player.getPresentingPlayerType()&&this.C.yu(this.u,"json3",function(d,e,f,h){if(d){a.C.EG()&&(a.W=[],a.J.Re("captions"),g.nn(a.X),a.ya.reset());var l=a.ya;f=f||0;h=h||0;if(l.B.Y("html5_disable_rawcc_killswitch")){if("string"!==typeof d){var m=new DataView(d);
8<=m.byteLength&&1718909296===m.getUint32(4)&&(m=g.dv(m,0,1835295092),d=d.slice(m.dataOffset,m.dataOffset+m.size),G2(d)||(d=g.$e(new Uint8Array(d))))}}else"string"===typeof d||G2(d)||(m=new DataView(d),d=8>=m.byteLength||1718909296!==m.getUint32(4)?"":(m=g.dv(m,0,1835295092))&&m.size?g.$e(new Uint8Array(d.slice(m.dataOffset,m.dataOffset+m.size))):"");if(d)try{if("string"!==typeof d){var n=d,p=f,r=h;if(!G2(n))throw Error("Invalid binary caption track data");l.u||(l.u=new F2(r,e));var t=l.u.C(n,p)}else{if("WEBVTT"===
d.substring(0,6))e=d,r=f,l.u||(l.u=new H2),p=l.u.C(e,r),.01>Math.random()&&g.nr(Error("Deprecated subtitles format in web player: WebVTT")),n=p;else b:{p=d;if("{"===p[0])try{l.u||(l.u=new o2(QFa(e)));n=l.u.C(p,f);break b}catch(H){g.$s(H);n=[];break b}r=g.A_(p);if(!r||!r.firstChild){var v=Error("Invalid caption track data");v.params=p;throw v;}if("timedtext"===r.firstChild.tagName){if(3===Number(r.firstChild.getAttribute("format"))){l.u||(l.u=new i2(QFa(e),l.B));n=l.u.C(r,f);break b}var x=Error("Unsupported subtitles format in web player (Format2)");
x.params=p;throw x;}if("transcript"===r.firstChild.tagName){var y=Error("Unsupported subtitles format in web player (Format1)");y.params=p;throw y;}var F=Error("Invalid caption track data");F.params=p;throw F;}t=n}var E=t}catch(H){g.$s(H),l.clear(),E=[]}else E=[];a.player.Kd(E);!a.da||a.aa||Q2(a)||g.ZD(a.B)||g.$D(a.B)||(g.sn(a.ea),E=qFa({Wh:0,Wg:5,Ii:5,Lk:2,textAlign:0,Ve:0,lang:"en"}),a.ka=[E],l=["Click "," for settings"],a.Aa||(t=new g.aM(g.qM()),g.C(a,t),a.Aa=t.element),t=E.end-E.start,(e=g.PH(a.u))&&
a.ka.push(new e2(E.start,t,0,E.id,e)),a.ka.push(new e2(E.start,t,0,E.id,l[0]),new e2(E.start,t,0,E.id,a.Aa,!0),new e2(E.start,t,0,E.id,l[1],!0)),a.player.Kd(a.ka),g.qn(a.ea));!a.da||a.aa||Q2(a)||(g.qE(a.B)?(0,g.Z_)(!0):R2(a,"module-enabled",!0),a.K&&(a.K.F=a.u),a.player.Zn());a.da=!1}}),!b||this.I||this.aa||Q2(this)||this.player.va("captionschanged",S1(this.u))),b||(this.u&&!Q2(this)?this.player.va("captionschanged",S1(this.u)):this.player.va("onCaptionsTrackListChanged"));
else{var c;this.Fa?c=new $1(this.videoData.u,this.player):this.Ua?c=new X1(this.B,this.videoData,this.player.getAudioTrack()):c=new a2(this.videoData.qg,this.videoData.videoId,this.videoData.captionsLanguagePreference||this.B.captionsLanguagePreference||g.TI(this.videoData,"yt:cc_default_lang")||this.B.We,this.videoData.Vo,this.B);this.C=c;g.C(this,this.C);c.zu(function(){var d;SFa(a)||a.da||RFa(a)?d=P2(a,a.da):N2(a)&&(d=O2(a));if(a.I||a.aa){for(var e=U1(a.C.B,!0),f=[],h=0;h<e.length;h++){var l=e[h],
m=g.He("TRACK");m.setAttribute("kind","subtitles");m.setAttribute("label",g.PH(l));m.setAttribute("srclang",T1(l));m.setAttribute("id",l.toString());a.aa||m.setAttribute("src",a.C.So(l,"vtt"));l===d&&m.setAttribute("default","1");f.push(m)}d=a.J.fd();d.nq(f);f=d.Zd();a.Ia&&a.ga.P(f.textTracks,"change",a.aQ)}else!a.u&&d&&S2(a,d),a.player.va("onCaptionsTrackListChanged"),a.player.va("onApiChange")})}};
R1.unload=function(){this.I&&this.u?TFa(this,!1):(this.ea&&g.sn(this.ea),this.player.Re("captions"),this.W=[],this.C&&this.C.Tk(),this.ya.clear(),this.L&&this.player.Kd(this.L),this.YA());g.zO.prototype.unload.call(this);this.player.Zn();this.player.va("captionschanged",{})};
R1.create=function(){this.Qn()&&this.load()};
R1.aQ=function(){for(var a=this.J.fd().Zd().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;var d=U1(this.C.B,!0);for(var e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.u:null)!==b&&S2(this,b,!0)};
R1.KR=function(){!this.u&&this.I||this.unload()};
R1.zd=function(a){this.W.push(a);g.nn(this.X)};
R1.rf=function(a){g.lb(this.W,a);this.C instanceof $1&&this.C.I&&this.player.Pf([a]);g.nn(this.X)};
R1.IQ=function(a){if(a instanceof f2){var b=this.U[a.id];b&&b.B!==a&&(b.dispose(),delete this.U[a.id],b=null);b||(b=UFa(this,a))&&(this.U[a.id]=b)}else b=a.windowId,this.la[b]||(this.la[b]=[]),this.la[b].push(a)};
R1.QQ=function(){VFa(this,this.ka);this.ka=null};
R1.MH=function(){var a=this;this.X.stop();g.Tb(this.la);this.W.sort(g.HG);var b=this.W;if(this.L){var c=g.Me(b,function(d){return-1===this.L.indexOf(d)},this);
c.length&&(b=c)}g.Cb(b,this.IQ,this);g.Eb(this.U,function(d,e){a.la[e]?(d.element.parentNode||(d instanceof d2||d instanceof c2||g.Hb(a.U,function(f,h){h!==e&&f.B.params.Wh===d.B.params.Wh&&f.B.params.Wg===d.B.params.Wg&&f.B.params.Ii===d.B.params.Ii&&(f.dispose(),delete a.U[h]);return h===e},a),g.nO(a.player,d.element,4)),d.Vp(a.la[e])):(d.dispose(),delete a.U[e])},this)};
R1.UQ=function(){K2(this,{},!0);g.P(this.B.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.va("captionssettingschanged")};
R1.WJ=function(){var a=T2.Jc;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.ii?3:a.bold?1:a.ii?2:0,textOpacity:a.textOpacity,windowColor:T2.windowColor,windowOpacity:T2.windowOpacity};var b=L2(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
R1.TH=function(a,b){var c={};g.Sa(c,L2(this,"display-settings"));g.Sa(c,a);K2(this,c,b);this.player.va("captionssettingschanged")};
R1.YA=function(){!this.I&&this.loaded&&(g.Eb(this.U,function(a,b){a.dispose();delete this.U[b]},this),this.MH())};
R1.He=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.de(b,-2,4);this.TH({fontSizeIncrement:c});return c;case "reload":b&&!this.I&&S2(this,this.u,!0);break;case "stickyLoading":void 0!==b&&this.B.C&&(g.qE(this.B)?(0,g.Z_)(!!b):R2(this,"module-enabled",!!b));break;case "track":if(!this.C)return{};if(b){if(this.I)break;if(!g.Oa(b))break;if(g.Sb(b)){S2(this,null,!0);break}for(var d=U1(this.C.B,!0),e=0;e<d.length;e++){var f=d[e];f.languageCode!==b.languageCode||c&&f.languageName!==b.languageName||
(c=b.translationLanguage?$Ea(f,b.translationLanguage):f)}!c||c===this.u&&this.loaded||S2(this,c,!0)}else return this.loaded&&this.u&&!Q2(this)?S1(this.u):{};return"";case "tracklist":return this.C?g.Nc(U1(this.C.B,!(!b||!b.includeAsr)),function(h){return S1(h)}):[];
case "translationLanguages":return this.C?this.C.F.map(function(h){return Object.assign({},h)}):[];
case "sampleSubtitles":this.I||void 0===b||WFa(this,!!b)}};
R1.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.B.C&&a.push("stickyLoading");return a};
R1.ly=function(){var a=this.u;return a?{cc:a.vssId}:{}};
R1.zR=function(){this.loaded&&this.u&&!Q2(this)?(g.qE(this.B)?(0,g.Z_)(!1):R2(this,"module-enabled",!1),this.unload(),N2(this,!0)&&S2(this,O2(this),!1)):S2(this,Q2(this)||!this.u?P2(this,!0):this.u,!0)};
R1.GN=function(){var a=Q2(this);N2(this,a)?S2(this,this.player.getAudioTrack().B,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.Qn()&&(a?S2(this,P2(this),!1):this.load()))};g.FO.captions=M2;})(_yt_player);
